In [54]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [55]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [60]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2025-10-15 00:44:39.134375
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2025-10-15 00:44:39.134375
2  10003    PREGO  BT10    100     60  z0019_2.csv 2025-10-15 00:44:39.134375

In [61]:
con.execute("""
    CREATE TABLE IF NOT EXISTS bronze_produtos (   
        NATBR VARCHAR,
        MAKTX VARCHAR,
        WERKS VARCHAR,
        MAINS VARCHAR,
        LABST VARCHAR,
        nome_arquivo VARCHAR,
        data_ingestao TIMESTAMP
    )    
""")

In [62]:
con.execute("INSERT INTO bronze_produtos SELECT * FROM df")

In [74]:
resultado_3 = con.execute("SELECT * FROM bronze_z0019").fetchdf()
resultado_3.head(6)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2025-10-15 00:43:49.890817
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2025-10-15 00:43:49.890817
2  10003     PREGO  BT10   100    50  z0019_1.csv 2025-10-15 00:43:49.890817
3  10004     SERRA  BT50   100   200  z0019_2.csv 2025-10-15 00:44:39.134375
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2025-10-15 00:44:39.134375
5  10003     PREGO  BT10   100    60  z0019_2.csv 2025-10-15 00:44:39.134375

In [72]:
con.execute("ALTER TABLE bronze_produtos RENAME TO bronze_z0019")

In [75]:
con.close()